REGION : "us-west-2"
KEY : "chef_west"
INSTANCE_TYPE : "m3.medium"
USER : "ec2-user"
S3_MAPPING_BUCKET : "builds.numenta.com"
YUM_REPO_TOOLS_PATH : "/opt/numenta/jenkins-ec2/operations-scripts/yumrepo-tools"
X86_64_REPO_PATH : "/opt/numenta/s3repo/s3/x86_64"
YUM_REPO: "/opt/numenta/s3repo/s3"
